### ISSUE TITLE
Library does not compile with ArduinoCore-mbed:v2.3.1

### ISSUE THREAD

**Issue by aentinger** [arduino-libraries/Arduino_MachineControl#64]
```bash
  /home/runner/Arduino/libraries/Arduino_MachineControl/src/Arduino_MachineControl.h:15:10: fatal error: USBHost.h: No such file or directory
   #include "USBHost.h"
```
See [this CI build](https://github.com/107-systems/107-Arduino-UAVCAN/pull/119/checks?check_run_id=3158447184#step:4:54).

**Comment by aentinger** [comment]
I've been using the wrong library, should have used https://github.com/arduino-libraries/Arduino_EdgeControl.
